SUMMARY = "Fast and embedded solvers for nonlinear optimal control"
HOMEPAGE = "https://docs.acados.org/"

LICENSE = "Apache-2.0 & BSL-1.0 & EXPAT & LGPL-2.1-only & LGPL-3.0-only & BSD-2-Clause & MIT &BSD-3-Clause"
LIC_FILES_CHKSUM = "file://LICENSE;md5=d0aae56f9abf0a648c46daaa9c9b0bba \
                    file://external/Clarabel.cpp/Clarabel.rs/LICENSE.md;md5=cd1ea1aa53f4de2f72ae90dd5ff74e8e \
                    file://external/Clarabel.cpp/LICENSE.md;md5=cd1ea1aa53f4de2f72ae90dd5ff74e8e \
                    file://external/blasfeo/LICENSE.txt;md5=32c816687e9a08fdeccc68f14604f6a8 \
                    file://external/catch/LICENSE.txt;md5=e4224ccaecb14d942c71d31bef20d78c \
                    file://external/daqp/LICENSE;md5=3c771722f28f7af4831a5e69d0a17157 \
                    file://external/hpipm/LICENSE.txt;md5=46f588b5b724984fee85c8d829b531e5 \
                    file://external/hpipm/experimental/andrea/prototype/code/plotregion/license.txt;md5=e2b0229fc6f74ce8a98a4bf49c0370a7 \
                    file://external/hpmpc/LICENSE.txt;md5=fbc093901857fcd118f065f900982c24 \
                    file://external/jsonlab/LICENSE_BSD.txt;md5=2a5a3d39f1fc4109bf3b3cd22de74184 \
                    file://external/jsonlab/LICENSE_GPLv3.txt;md5=f2780469a3abc95149f493ee44b89df2 \
                    file://external/osqp/LICENSE;md5=8e2ec41c8eab21d2e1bd5c7457cfc34c \
                    file://external/osqp/lin_sys/direct/qdldl/amd/LICENSE;md5=0bbe43b2d874f66e6ab5e8c55beeb405 \
                    file://external/osqp/lin_sys/direct/qdldl/qdldl_sources/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327 \
                    file://external/qpdunes/LICENSE;md5=c8156b3403995b12675506b785491cd2 \
                    file://external/qpoases/LICENSE.txt;md5=fbc093901857fcd118f065f900982c24 \
                    file://utils/license/acados_license.txt;md5=2550b316f62fec0e8345bfbb1c913c7c \
                    file://utils/license/casadi_autogenerated_license.txt;md5=44474904a00a2865ca5e90c934917aca \
                    file://utils/license/license.c;md5=cc3e36364d6ba896f61cf43301a5b66b \
                    file://utils/license/license.py;md5=a62ff36cc8828b63363000b3fe16e471"

SRC_URI = "git://github.com/acados/acados;protocol=https;name=acados;branch=main \
           git://github.com/giaf/hpmpc.git;protocol=https;name=hpmpc;branch=master;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/hpmpc \
           git://github.com/giaf/blasfeo.git;protocol=https;name=blasfeo;branch=master;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/blasfeo \
           git://github.com/acados/qpDUNES-dev.git;protocol=https;name=qpdunes;branch=master;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/qpdunes \
           git://github.com/catchorg/Catch2.git;protocol=https;name=catch;branch=devel;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/catch \
           git://github.com/giaf/hpipm.git;protocol=https;name=hpipm;branch=master;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/hpipm \
           git://github.com/acados/qpOASES.git;protocol=https;name=qpoases;branch=master;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/qpoases \
           git://github.com/osqp/osqp.git;protocol=https;name=osqp;branch=master;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/osqp \
           git://github.com/osqp/qdldl.git;protocol=https;name=qdldl;branch=master;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/osqp/lin_sys/direct/qdldl/qdldl_sources \
           git://github.com/acados/tera_renderer;protocol=http;name=tera_renderer;branch=master;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/interfaces/acados_template/tera_renderer \
           git://github.com/fangq/jsonlab.git;protocol=https;name=jsonlab;branch=master;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/jsonlab \
           git://github.com/acados/test_data;protocol=http;name=testdata;branch=master;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/examples/acados_python/tests/test_data \
           git://github.com/darnstrom/daqp.git;protocol=https;name=daqp;branch=acados;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/daqp \
           git://github.com/acados/Clarabel.cpp.git;protocol=https;name=clarabelcpp;branch=migrate_july25;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/Clarabel.cpp \
           git://github.com/oxfordcontrol/Clarabel.rs.git;protocol=https;name=clarabelrs;branch=main;subdir=${BB_GIT_DEFAULT_DESTSUFFIX}/external/Clarabel.cpp/Clarabel.rs \
           file://disable-cmake-make-program-override.patch \
           file://disable-compiler-options.patch \
           file://fix-qproblemcpy.patch \
           file://remove-unused-argument.patch \
           file://fix-cmake-install-destination.patch \
"

PV = "0.5.5+git"
SRCREV = "59d93e17d2985fdd73fc58b8a83ed8f83a024171"
SRCREV_clarabelcpp = "c73eb64352f17fc18bc10fe3c082fcbf9a3c0487"
SRCREV_clarabelrs = "25540f559592068d0c8a80e46ded1b21760212a1"
SRCREV_blasfeo = "d6251233923c9b475fe894fb729fb63ab693e301"
SRCREV_catch = "191fa38c9b1596cd2576ab531d4ab4d5e8e05190"
SRCREV_daqp = "b84fe8716325db90b4ef3ee3969f92cf045a4931"
SRCREV_hpipm = "e3a56c1caddd7f12d125d84f337b9a9e5c186271"
SRCREV_hpmpc = "da0f9791034cb09bb0904d73504e948d8ea4d0a5"
SRCREV_jsonlab = "288dc922ab94bec42405541e7f50036d9716c5d7"
SRCREV_osqp = "0dd00a578cf1c2691c5c379965d504c75bf6cfad"
SRCREV_qdldl = "7d16b70a10a152682204d745d814b6eb63dc5cd2"
SRCREV_testdata = "c95aa6fd2d1ae4ee202dbafe935d8987aa62b73c"
SRCREV_qpdunes = "4f5bdb4ff19a4a2896abe5bfd8fbde5710f34950"
SRCREV_qpoases = "125e94fa638f00350608871fc165789b1d1762f1"
SRCREV_tera_renderer = "c41c5a03a03a42d3ac5084ddcd415502f7721b05"

SRCREV_FORMAT = "acados"

inherit cmake

BLASFEO_TARGET = "${@get_blasfeo_target(d)}"

# BLASFEO can't detect the target CPU
#   List of values: https://github.com/giaf/blasfeo/blob/master/README.md
def get_blasfeo_target(d):
    tune = d.getVar('TUNE_FEATURES').split()

    if 'avx512' in tune:
        return 'X64_INTEL_SKYLAKE_X'
    if 'avx2' in tune:
        return 'X64_INTEL_HASWELL'
    if 'cortexa76' in tune:
        return 'ARMV8A_ARM_CORTEX_A76'
    if 'cortexa57' in tune or 'cortexa72' in tune:
        return 'ARMV8A_ARM_CORTEX_A57'
    if 'cortexa53' in tune:
        return 'ARMV8A_ARM_CORTEX_A53'

    return 'GENERIC'

# HPIPM_TARGET can be AVX or GENERIC
HPIPM_TARGET = "${@get_hpipm_target(d)}"
def get_hpipm_target(d):
    tune = d.getVar('TUNE_FEATURES').split()

    if 'avx512' in tune:
        return 'AVX'
    if 'avx2' in tune:
        return 'AVX'

    return 'GENERIC'

EXTRA_OECMAKE += " \
    -DBLASFEO_TARGET=${BLASFEO_TARGET} \
    -DHPIPM_TARGET=${HPIPM_TARGET} \
    -DACADOS_WITH_QPOASES=ON \
    -DACADOS_WITH_OPENMP=OFF \
"

DEPENDS = "libeigen"

FILES:${PN} += "${libdir}/*${SOLIBSDEV}"
INSANE_SKIP:${PN} = "dev-so"

FILES:${PN}-dev = " \
    ${datadir}/*/cmake \
    ${includedir} \
    ${prefix}/src/debug \
"
