# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "atmos-layer"
BBFILE_PATTERN_atmos-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_atmos-layer = "6"

LAYERDEPENDS_atmos-layer = "core"
LAYERSERIES_COMPAT_atmos-layer = "wrynose"
